#----------------------------------------
# Rutulys compiler config file
#----------------------------------------

# Path
#---------------------------------------

# Deploy directory (its parent directory must be writable)
deploypath: './www'


# Settings
#---------------------------------------

# WWW base path
baseuri: 'http://www.example.com/path/to/base'

# Used for strftime in generating HTML
timeformat: '%b %-d, %Y %H:%M:%S %Z'

