#----------------------------------------
# Rutulys compiler config file
#----------------------------------------

# Path
#---------------------------------------

# Deploy directory (its parent directory must be writable)
deploypath: './www'


# Settings
#---------------------------------------

# WWW base path
baseuri: 'http://www.example.com/path/to/base'

# Article modification date format
timeformat: '%b %-d, %Y %H:%M:%S %Z'

# Article modification date format for category page
categorydate: '%b %-d, %Y'

# Category name list for displaying categories more pretty
categoryname:
  foo: "Foo"
  bar: "BAR"

